Export changes:
[netlog_viewer] Set description for QUIC_SESSION_POOL_JOB

The event provides the `host` parameter. Use it as description.

Bug: chromium:40286648
Change-Id: I2866683dd03eb646d4225ed8705256c621435537
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/5266527
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
(cherry picked from commit c2c3cef34d1a1cee17fffcf34c98a6a9a352d064)

[NSP] Update remaining Network Isolation Key references

For things that were updated to use the Network Anonymization Key
instead of the Network Isolation Key, make the corresponding keys
in the Net Log viewer (for the cases of this that remain).

The one real JS change here corresponds to:
https://chromium-review.googlesource.com/c/chromium/src/+/3927863/13/net/network_error_logging/network_error_logging_service.cc#257:~:text=Set(%22-,NetworkAnonymizationKey,-%22%2C

Bug: chromium:1435397
Change-Id: I6a07fddf3943bdc9a06fa476aa9366a1d1d34e83
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4776382
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Andrew Williams <awillia@chromium.org>
(cherry picked from commit af1b9a8fa64eb4c5ba05782f90e5c2142277735f)

Replace network_isolation_key key usage in NetLog viewer

As part of the network state partitioning project, the Chrome code
was updated to use the key `network_anonymization_key` instead of
`network_isolation_key` for several NetLog dictionaries, but
corresponding changes in the NetLog viewer code was missed. This
updates this for multiple cases, where the corresponding Chrome
code can be found at:

https://source.chromium.org/chromium/chromium/src/+/main:net/reporting/reporting_cache_impl.cc;l=1603;drc=b8946d11846c93f6a640570f4edcd23b78b1d454
https://source.chromium.org/chromium/chromium/src/+/main:net/reporting/reporting_cache_impl.cc;l=105;drc=b8946d11846c93f6a640570f4edcd23b78b1d454
https://source.chromium.org/chromium/chromium/src/+/refs/heads/main:net/dns/host_cache.cc;l=936;drc=a564d91c7da9f973a82851f81d3107eb2879d707

Bug: chromium:1435397
Change-Id: Ic0962819c018bebf718867ba3c17666b6dc90b1a
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4604510
Commit-Queue: Jincheol Jo <jincheol.jo@navercorp.com>
Reviewed-by: John Chen <johnchen@chromium.org>
Reviewed-by: Andrew Williams <awillia@chromium.org>
Reviewed-by: Matt Mueller <mattm@chromium.org>
(cherry picked from commit b5014c42b5795ed208204dde06f452306580b8f7)

netlog_viewer: add parameter writer for CERT_VERIFY_PROC_PATH_BUILT

Bug: chromium:634484
Change-Id: I7495f7f8a0411952ebbfc4c0a0f0e71af4d86af1
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4574847
Reviewed-by: David Benjamin <davidben@chromium.org>
Commit-Queue: Matt Mueller <mattm@chromium.org>
(cherry picked from commit 5b509eb8b0ae35624169ec5af3588801eec8dbe5)

netlog_viewer: add parameter writers for CERT_VERIFY_PROC and CERT_VERIFY_PROC_PATH_BUILD_ATTEMPT

Bug: chromium:634484
Change-Id: I249869828d74635dec7fe47959f6e96d65c17d8b
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4575170
Reviewed-by: David Benjamin <davidben@chromium.org>
Commit-Queue: Matt Mueller <mattm@chromium.org>
(cherry picked from commit 3495a7bd1f7bd18b80d531f3ab9e4b5ae24582ab)

netlog_viewer: make default events view left pane wider

Change-Id: Ia422cb3274481dd8ca44c114e439670dc23f96e2
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4574848
Reviewed-by: David Benjamin <davidben@chromium.org>
Commit-Queue: Matt Mueller <mattm@chromium.org>
(cherry picked from commit 40dcb3cb9d8e8379ed58d092ce477b35e20635b9)

netlog_viewer: show hostname as description for CERT_VERIFIER_TASK

Bug: chromium:634484
Change-Id: I7b82ce03a249113f629f20fc877b496fa27f0e70
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4568657
Commit-Queue: Matt Mueller <mattm@chromium.org>
Reviewed-by: David Benjamin <davidben@chromium.org>
(cherry picked from commit 44beba1e6d819a2154b069bc1fd76878b47f33d1)

[netlog_viewer] Add ParameterOutputter.writeArrowKeyJSONValue()

To prettify the output of a JSON object.

Bug: chromium:1345530
Change-Id: I6195912026d9eaea9814246cb555baa3835c4184
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4522581
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
Reviewed-by: Matt Mueller <mattm@chromium.org>
(cherry picked from commit 8f7d68d6ce88011dfbae37c2cdc4a51177a179da)

netlog-viewer: Show DNS_OVER_HTTPS event source nicely

Now a NetLog can contain DNS_OVER_HTTPS event source and
DOH_URL_REQUEST event type. Show DNS_OVER_HTTPS sources as DNS related
sources. Also set the description of DOH_URL_REQUEST to the URL of
a DoH request.

Bug: chromium:1345530
Change-Id: Ifa8ab9dbc7aa9e5b8c49d97f5fbf8306292caec2
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4301790
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
(cherry picked from commit 4003278e8cd1d54ca0660ea4e39744eb842c7a91)

netlog-viewer: Fix log_view_painter_test

https://crrev.com/c/1827489 removed MAYBE_USER_GESTURE. Tests needs
to be updated.

This CL also changes actual/expected comparison to per line. It
makes debugging easier.

This is a preparation to update netlog-viwer for the associated bug.

Bug: chromium:1345530
Change-Id: I2c3b56d021ff1aa0386e77138c292e64bc5578cf
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/4301770
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
Reviewed-by: Matt Menke <mmenke@chromium.org>
(cherry picked from commit bf3c3fae5355dd8a1ae7c6b199681eb134ff6add)

Remove MAYBE_USER_GESTURE load flag

The MAYBE_USER_GESTURE load flag was already removed in
https://chromium-review.googlesource.com/c/chromium/src/+/1827489, so
this CL is just removing mentions of it in the netlog viewer code/tests.

Bug: chromium:426442, chromium:516495
Change-Id: I0fd77ca57e7c522beac419adf5f8391f93dd3205
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3844851
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Nidhi Jaju <nidhijaju@chromium.org>
(cherry picked from commit 0f2664f81853b5ed6fa2961f40e4eb1977ae788c)

[NetLog Viewer] Drop optional-chaining operator and upgrade Flask

I ran into a few issues while trying to follow the deployment
instructions linked from [0].

When I tried to run build_for_appengine.py, I saw that vulcanize was
failing when it hit the JavaScript optional-chaining operator (`?.`) in
dns_view.js. Apparently, vulcanize is deprecated and its last release
was five years ago in 2017. I tried out its successor, polymer-bundler,
but that suffered from a less verbose variant of the same problem; it
just silently failed to inline the dns_view.js script as well as the JS
file that defines `Polymer`, which caused a number of runtime failures
on load.

We should probably replace vulcanize with a new bundler, but I'm not
sure that polymer-bundler is a good idea. The Polymer library appears to
be deprecated as well, but maybe that doesn't include the CLI tool [1]?
Perhaps we should pick a new bundler entirely or just build something
ourselves with Golang's "text/template" library.

After generating the bundle, I tried to run the appengine dev server,
but that failed with a Python import error (see below). I noticed that
requirements.txt was asking for a very old version of Flask that was
released in 2013 [2]. I bumped the version to the latest release, and
the import error went away. I didn't investigate this one very
thoroughly.

    catapult/netlog_viewer/appengine % dev_appserver.py app.yaml
    [...]
    ImportError: cannot import name 'Markup' from 'jinja2' (/tmp/tmppe8EAp/lib/python3.9/site-packages/jinja2/__init__.py)

[0]: https://chromium.googlesource.com/catapult/+/master/netlog_viewer/CONTRIBUTING.md#deploying-to-netlog_viewer_appspot_com
[1]: https://polymer-library.polymer-project.org/
[2]: https://pypi.org/project/Flask/0.10.1/

Bug: chromium:1319431
Change-Id: Ic61533edfc9ee2ebaa14dffdb8192f64fa2eafcb
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3606688
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Dan McArdle <dmcardle@chromium.org>
(cherry picked from commit 6657a0631127618d16384384f728a13d6f96d87e)

[NetLog Viewer] Resolve TODOs from M59 and M87 in dns_view.js

* Drop the valueOrDefault function, which was used only for host cache
  fields that might not exist prior to M59.
* Drop the support for pre-M87 `error` (now it's just `net_error`).
* (Unrelated) Clean up Array detection with `Array.isArray()`.

Bug: chromium:1312236
Change-Id: I300656ce136be665532cd6ec998a839647a31aea
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3563511
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Dan McArdle <dmcardle@chromium.org>
(cherry picked from commit 88422dcb3f96c90202311f26f99e75e73363e343)

[NetLog Viewer] Fix logic behind "Internal DNS client enabled"

Other changes:

* Add link to //net/dns/README.md documentation.

* Fix a data-clearing bug. Importing a second net log would just append
  the new disabled DoH providers to the old ones without clearing.

* Delete logic for detecting invalid config, which just checked whether
  nameservers had any values.

Bug: chromium:1078403
Change-Id: Ida00c92c32d60add45fdfd58ec9347e1e43e30be
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3557818
Reviewed-by: Eric Orth <ericorth@chromium.org>
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Dan McArdle <dmcardle@chromium.org>
(cherry picked from commit a074c9cbd6af71f4bda11d765aa27f3f7dae8a47)

[NetLog Viewer] Use the new ip_endpoints field of cache entries

The error in the linked bug was already partially resolved by
https://chromium-review.googlesource.com/c/catapult/+/3526853

However, it silently ignores the new ip_endpoints field introduced in
https://chromium-review.googlesource.com/c/chromium/src/+/3288069/

This CL shows any legacy `addresses` as well as the new `ip_endpoints`
in the "Addresses" column of the DNS view.

Bug: chromium:1312346
Change-Id: Ifcad8adf680f81766e57d1df756dd5a0da2910f5
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3565560
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Dan McArdle <dmcardle@chromium.org>
Auto-Submit: Dan McArdle <dmcardle@chromium.org>
(cherry picked from commit a9d86a4042d785f34683f1306109c3bf11713c98)

[NetLog Viewer] Stringify DnsConfig array elements

displayAsyncDnsConfig_() was incorrectly passing an array of objects to
addListToNode_(), which requires an array of strings. This meant that
the value corresponding to "doh_config" (which replaced "dns_servers")
was rendering as "[object Object]".

Bug: chromium:1176520
Change-Id: Icbc04ac8bcb71b6addfe5e64bb1cf3022d4fe2c2
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3556369
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Dan McArdle <dmcardle@chromium.org>
(cherry picked from commit e78aa0b2341baa63182ee23bf27d429ac9f3789b)

[NetLog Viewer] Support new location of disabled DoH providers

We are moving the list of disabled DoH providers out of the DnsConfig
[0]. As of CL 3526375, it is emitted by GetNetInfo() [1]. This change
adds support for the new location and continues implicitly supporting
the old format, since DnsView just iterates over the DnsConfig fields.

This change also fixes a bug I ran into in DnsView where
onHostResolverInfoChanged() tried to render the addressess associated
with a cache entry. Not all entries are guaranteed to have addresses!

[0]: https://chromium-review.googlesource.com/c/chromium/src/+/3515012
[1]: https://chromium-review.googlesource.com/c/chromium/src/+/3526375

Bug: chromium:1300296
Change-Id: I912129d6c07634da3f4ccabf107c1b1b9b73ba1d
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3526853
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Dan McArdle <dmcardle@chromium.org>
(cherry picked from commit 19e5fdf6c7dad4ebc26a22c3465aad0c44df0eb1)

[Netlog Viewer] Add network isolation key to Reporting/NEL view

This adds Network Isolation Key associated with reports and endpoint
configurations to the Reporting page in the Netlog viewer.

NOPRESUBMIT=true
Bug: chromium:1035629
Change-Id: I3e23511c603f6d29d82434a884c7ec1e6269c614
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3498123
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Kunihiko Sakamoto <ksakamoto@chromium.org>
(cherry picked from commit 1ec1fe1b1334d0851051b8f2263d44af8a198ddd)

[NetLog Viewer] Fix netInternalsLogViewPainterPrintAsText test

It seems the test was broken since https://crrev.com/c/1378845.
Rename "hex_encoded_bytes" parameter to "bytes" and update values
to Base64 encoded bytes.

Bug: chromium:1270163
Change-Id: I9c71a46701cdd54b54c68d1db26c74b5775c24c9
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3284243
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
(cherry picked from commit 1a5ffbc5f1b40458da2fa20082d5a93db35665de)

[NetLog Viewer] Fix tests.html

tr.b.unittest.loadAndRunTests() is available only after
HTMLImports.whenReady().

Bug: chromium:1270163
Change-Id: I30aaeaa9a96db18af84aaf8df50fa28566cc3413
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3280882
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
(cherry picked from commit af0bc200002e378a9e4c09b2730829081caaa986)

[NetLog Viewer] Show description for WEB_TRANSPORT_CLIENT event source

crrev.com/c/3268277 added URL to a WEB_TRANSPORT_CLIENT alive event.
Use it as event source description in a way similar to URL_REQUEST.

Change-Id: Ic14d1803006d373836591dc5e9fd1316fc91d025
Reviewed-on: https://chromium-review.googlesource.com/c/catapult/+/3276079
Reviewed-by: Matt Menke <mmenke@chromium.org>
Commit-Queue: Kenichi Ishibashi <bashi@chromium.org>
(cherry picked from commit a7ad5b5c96b3ec2d70ea5c173a15ef45cacaf07a)